export const data = {
  nav: {
    home: "home",
    about: "About",
    contact: "Contact",
  },
  hero: [
    {
      id: 1,
      link: "/en/projects",
      class:
        "px-6 py-3 bg-slate-700 text-white rounded-lg hover:bg-slate-800 transition",
      label: "📁 See Projects",
      target: "_self",
    },
    {
      id: 2,
      link: "https://jimmygarcia.dev/assets/pdf/CV-EN-Jimmy-Ernesto-Garcia-Contreras-Fullstack-Developer.pdf",
      class:
        "px-6 py-3 border border-slate-700 text-slate-700 rounded-lg hover:bg-slate-700 hover:text-white transition dark:text-slate-300 dark:border-slate-500 dark:hover:text-white",
      label: "📄 Download CV",
      target: "_blank",
      disabled: true,
    },
    {
      id: 3,
      link: "https://drive.google.com/embeddedfolderview?id=1HuxX2ugTGpsAFGZdvTwGOI6M04tYWCpQ#grid",
      class:
        "px-6 py-3 border border-slate-400 text-slate-700 dark:text-slate-300 dark:border-slate-600 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition",
      label: "🏆 View Certificates",
      target: "_blank",
    },
    {
      id: 4,
      link: "https://www.linkedin.com/in/jimmyegc",
      class:
        "px-6 py-3 border border-slate-400 text-slate-700 dark:text-slate-300 dark:border-slate-600 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition",
      label: "💼 LinkedIn",
      target: "_blank",
    },
    {
      id: 5,
      link: "https://github.com/jimmyegc",
      class:
        "px-6 py-3 border border-slate-400 text-slate-700 dark:text-slate-300 dark:border-slate-600 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition",
      label: "🐙 GitHub",
      target: "_blank",
    },
  ],
  menu: [
    {
      id: 1,
      link: "/projects",
      label: "All projects",
    },
    {
      id: 2,
      link: "/contact",
      label: "Contact me",
    },
  ],
  portfolio: {
    id: 1,
    name: "Jimmy Ernesto García Contreras",
    shortName: "Jimmy García",
    about:
      "💻 Full Stack Developer with 20+ years of experience building tech solutions for logistics, operations, and SMBs in the automotive sector. Skilled at modernizing legacy systems and delivering efficient, scalable applications that drive business impact.🚀 Passionate about continuous learning and tackling challenges that turn ideas into real projects.👉 Open to new opportunities and collaborations to create solutions that make a difference.",
    baseUrl: "https://jimmygarcia.dev",
    projects: [
      {
        id: 1,
        date: "44927",
        brick: 4,
        title: "Recruitment with Augmented Reality",
        client: "Tupperware Brands México",
        liveUrl: "https://twmx-prototipo-ar.netlify.app/",
        category: "Mobile",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--hdL2h1U---/ar_1:1,c_fill,h_400,w_400/v1751512372/Proyectos/Prototipo%20para%20Reclutamiento%20con%20AR/prototype-ar-thumbnail_bredup_drsmid.webp",
        isFeatured: true,
        description:
          "I developed a prototype with Augmented Reality that was used for Recruitment. I made a Web application with Vue/HTML/CSS/JavaScript also using Google's ''Model viewer'' technology to render 3D objects and show augmented reality.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--z4jEX24w--/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1/Proyectos/Prototipo%20para%20Reclutamiento%20con%20AR/prototype-ar-001_f8wm9z.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--AtvMhPcI--/ar_1:1,c_fill,g_auto,w_1000/v1695253559/Proyectos/Prototipo%20para%20Reclutamiento%20con%20AR/prototype-ar-002_ayl2on.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--RtmV79VO--/ar_1:1,c_fill,g_auto,w_1000/v1695253561/Proyectos/Prototipo%20para%20Reclutamiento%20con%20AR/prototype-ar-003_h3jflh.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--gMoYqmVV--/v1695253563/Proyectos/Prototipo%20para%20Reclutamiento%20con%20AR/prototype-ar-004_cv3lwd.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--wsuhxwOD--/v1695253565/Proyectos/Prototipo%20para%20Reclutamiento%20con%20AR/prototype-ar-005_wjmc22.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--425vORHE--/v1695253551/Proyectos/Prototipo%20para%20Reclutamiento%20con%20AR/prototype-ar-006_u2sxlg.jpg",
        ],
        technologies: "HTML, CSS, JavaScript, Vue, Model-viewer (Google)",
      },
      {
        id: 2,
        date: "44562",
        brick: 4,
        title: "Trendsetter",
        client: "Tupperware Brands México",
        liveUrl: "https://youtu.be/ly9q2jpGlIA",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--XWvAS99g--/ar_1:1,c_fill,g_auto,w_1000/v1695265760/Proyectos/Trendsetter/trendsetter-thumbnail_zpztut.png",
        isFeatured: false,
        description:
          "Web application to know the sales force's product capture trends. This application contains the administration of users, campaigns, validity periods, parameters, capture and consultation of orders and reports.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--O_ok089_--/v1695265761/Proyectos/Trendsetter/trendsetter-thumbnail-001_tb2jmu.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--mavdCrAY--/v1695265761/Proyectos/Trendsetter/trendsetter-thumbnail-002_apqj8g.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--sLWUt2no--/v1695265761/Proyectos/Trendsetter/trendsetter-thumbnail-003_qdd5ds.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--oczTVJJg--/v1695265761/Proyectos/Trendsetter/trendsetter-thumbnail-004_dslslp.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--2X9pWVnF--/v1695265760/Proyectos/Trendsetter/trendsetter-thumbnail_zpztut.png",
        ],
        technologies: "HTML, CSS, JavaScript, Vue, Tailwind CSS, Flowbite",
      },
      {
        id: 3,
        date: "44562",
        brick: 4,
        title: "Sale of employees",
        client: "Tupperware Brands México",
        liveUrl: "https://youtu.be/5ubz1ykhbOI",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--8LwCHj4z--/t_Thumbnail/v1/Proyectos/Venta%20de%20Empleados/sale-employee-thumbnail_qthxwg.webp",
        isFeatured: true,
        description:
          "Web Application for Employee Sales for internal use, the migration of a monolithic application was made, making improvements in performance, design and usability. It has access to users, sales administration, payment types, product loading, categories, reports, and email notification.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--2QbJEONH--/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1/Proyectos/Venta%20de%20Empleados/sale-employee-thumbnail_qthxwg.png",
        ],
        technologies: "HTML, CSS, JavaScript, Vue",
      },
      {
        id: 4,
        date: "44562",
        brick: 4,
        title: "Event Attendance Registration",
        client: "Tupperware Brands México",
        liveUrl: "https://youtu.be/kxELQJaDvu4",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--l-Y1Gm4f--/t_Thumbnail/v1/Proyectos/App%20de%20Eventos/Captura_de_pantalla_2023-09-15_204622_dwvftn.webp",
        isFeatured: true,
        description:
          "App for the Events area that allowed you to pre-register the 2022 Convention Attendees, keep track of their attendance using your digital ticket by scanning the QR code, in addition to keeping track of the Delivery of the gifts that were received. performed at in-person events. It also has analytics, reports and statistics for operators.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--po95pt1u--/v1695256780/Proyectos/App%20de%20Eventos/events-005_u5g1ad.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--74vAAqsg--/ar_1:1,c_fill,g_auto,w_1000/v1695266705/Proyectos/App%20de%20Eventos/events-007_va4o1t.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--Jg1EnhyN--/v1695256783/Proyectos/App%20de%20Eventos/events-006_ydlefn.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--lg2tTvkw--/v1695256788/Proyectos/App%20de%20Eventos/events-001_lfl0q5.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--QAf34V_8--/v1695256791/Proyectos/App%20de%20Eventos/events-003_f6mpyt.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--f_HWIMT3--/v1695256777/Proyectos/App%20de%20Eventos/events-004_vejr2v.png",
        ],
        technologies: "HTML, CSS, JavaScript, Vue, NodeJs, Express, Firebase",
      },
      {
        id: 5,
        date: "43831",
        brick: 4,
        title: "Support Apps",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--_KQ8xVc9--/ar_1:1,c_fill,g_auto,w_1000/v1695432555/Proyectos/Apps%20de%20Soporte/soporte-001_moic6z.png",
        isFeatured: false,
        description:
          "Applications that you develop to provide support to Our Sales Force. Such as for forgotten #SoyTupperware password, frequently asked questions from users, uploading information from catalogs, unique offer, sending notification, etc. All the applications were made when third-party solutions did not have it, so they arise from a need and alternative. All using new frameworks such as Vue, NodeJs, BulmaCSS, TailwindCSS, Vuetify, etc.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--yGWtHDX9--/v1695432555/Proyectos/Apps%20de%20Soporte/soporte-thumbnail_vs6wnk.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--0sbrBCpf--/v1695432555/Proyectos/Apps%20de%20Soporte/soporte-001_moic6z.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--6dmV9WBr--/v1695432556/Proyectos/Apps%20de%20Soporte/soporte-002_ggk3ne.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--T91dkICY--/v1695432554/Proyectos/Apps%20de%20Soporte/soporte-003_mie2vi.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--ixn9csBw--/v1695432555/Proyectos/Apps%20de%20Soporte/soporte-004_uj7peg.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--vy3A_JDe--/v1695432556/Proyectos/Apps%20de%20Soporte/soporte-005_alf5gc.png",
        ],
        technologies:
          "HTML, CSS, JavaScript, Vue, .NET, Microsoft SQL Server, Firebase, Google Docs, Vuetify, BulmaCSS, ",
      },
      {
        id: 6,
        date: "43831",
        brick: 4,
        title: "Prototype (Thank You Day)",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--Vokm58C_--/ar_1:1,c_fill,g_auto,w_1000/v1695433160/Proyectos/Demo%20d%C3%ADa%20del%20agradecimiento/agradecimiento-thumbnail_qvothe.png",
        isFeatured: false,
        description:
          "This was a prototype of an Application that was responsible for sending digital postcards among associates. My focus was learning Vue during the pandemic, so this was one of my first projects with that Framework. I loved how it looks compared to the original App. This was also developed with Vue, BulmaCSS.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--8kQo5yY7--/v1695433160/Proyectos/Demo%20d%C3%ADa%20del%20agradecimiento/agradecimiento-thumbnail_qvothe.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--tp2Y-KgK--/v1695433158/Proyectos/Demo%20d%C3%ADa%20del%20agradecimiento/agradecimiento-001_ksji6x.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--MseNDWgd--/v1695433157/Proyectos/Demo%20d%C3%ADa%20del%20agradecimiento/agradecimiento-002_il4925.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--O-Tpw0qt--/v1695433156/Proyectos/Demo%20d%C3%ADa%20del%20agradecimiento/agradecimiento-003_j8g8cv.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--ugX6An3b--/v1695433159/Proyectos/Demo%20d%C3%ADa%20del%20agradecimiento/agradecimiento-004_ddcekh.png",
        ],
        technologies: "HTML, CSS, JavaScript, Vue, NodeJs, BulmaCSS",
      },
      {
        id: 7,
        date: "43466",
        brick: 4,
        title: "App to Upload Photos of the Sales Force",
        client: "Tupperware Brands México",
        liveUrl: "https://youtu.be/4Dl-1tPxNCY",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--MppJQsHY--/ar_1:1,c_fill,g_auto,w_1000/v1695437660/Proyectos/Carga%20de%20Fotografias/fotografias-thumbnail_n9qrjb.png",
        isFeatured: false,
        description:
          "I developed an application that allows the Sales Force to upload the photographs that the Events department requested for digital Events. I used the Vue framework for the Frontend and the Backend was created in NodeJs and Firebase.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--XnvZ_hSK--/v1695437660/Proyectos/Carga%20de%20Fotografias/fotografias-thumbnail_n9qrjb.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--wMGJPhlA--/v1695437624/Proyectos/Carga%20de%20Fotografias/fotografias-001_ibnuvd.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--pN-Mg-nl--/v1695437659/Proyectos/Carga%20de%20Fotografias/fotografias-002_tzr3hx.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--Gw9HyrcF--/v1695437657/Proyectos/Carga%20de%20Fotografias/fotografias-003_w8r19b.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--LWVZZQDD--/v1695437662/Proyectos/Carga%20de%20Fotografias/fotografias-004_eca3wr.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--GrcjkXh2--/v1695437663/Proyectos/Carga%20de%20Fotografias/fotografias-005_gmsexr.png",
        ],
        technologies: "HTML, CSS, JavaScript, Vue, Vuetify, NodeJs, Firebase",
      },
      {
        id: 8,
        date: "43466",
        brick: 4,
        title: "Digital raffles for HR and Events",
        client: "Tupperware Brands México",
        liveUrl: "https://youtu.be/iTL-mu1ZUnw",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--UoyfTPIX--/ar_1:1,c_fill,g_auto,w_1000/v1695785447/Proyectos/Rifas%20digitales/rifas-005_irtf7s.png",
        isFeatured: false,
        description:
          "Developed several sites that were used for Human Resources Raffles and digital Events. The idea is to be able to run the giveaways using a web page using HTML, CSS and JavaScript. In addition to supporting the Human Resources area in voting on values at the end of the year dinner.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--bZ1qJ24J--/v1695785091/Proyectos/Rifas%20digitales/rifas-001_utgntu.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--KBacX0eV--/v1695785090/Proyectos/Rifas%20digitales/rifas-002_ftwzyn.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--JmHPKfbk--/v1695785091/Proyectos/Rifas%20digitales/rifas-003_vg6oss.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--w8WMEgcE--/v1695785446/Proyectos/Rifas%20digitales/rifas-004_pw50hq.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--fbT0_yxL--/v1695785447/Proyectos/Rifas%20digitales/rifas-005_irtf7s.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--12WIMAzR--/v1695785446/Proyectos/Rifas%20digitales/rifas-006_fheheu.png",
        ],
        technologies: "HTML, CSS, JavaScript",
      },
      {
        id: 9,
        date: "43101",
        brick: 4,
        title: "Digital Coupon for Shopify Sales Force",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--Os0sWcO---/ar_1:1,c_fill,g_auto,w_1000/v1695438463/Proyectos/Cupon%20Descuento/cupon-thumbnail_mywoob.png",
        isFeatured: false,
        description:
          "I developed an application that allowed the Sales Force to personalize the discount coupon. The coupon was generated with the Shopify API and was dynamic according to the user's information. The site is made with Vue and BulmaCSS.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--AyCGbLcV--/v1695438463/Proyectos/Cupon%20Descuento/cupon-thumbnail_mywoob.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--B6H1ovQH--/v1695438458/Proyectos/Cupon%20Descuento/cupon-001_jod4w0.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--CgMmxvZa--/v1695438461/Proyectos/Cupon%20Descuento/cupon-002_vbof98.png",
        ],
        technologies: "HTML, CSS, JavaScript, Vue, Shopify",
      },
      {
        id: 10,
        date: "43101",
        brick: 4,
        title: "Virtual Assistant (Chatbot) for WhatsApp",
        client: "Tupperware Brands México",
        liveUrl: "https://youtu.be/KmQ6NxhQoSU",
        category: "Mobile",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--tD7hTJD4--/ar_1:1,c_fill,g_auto,w_1000/v1695950884/Proyectos/Tupperchat/tupperchat-thumbnail_cuce5c.png",
        isFeatured: false,
        description:
          "Programming the Virtual Assistant (Menus, content, API, Digital Coupon) for WhatsApp and integrating it with internal services. Develop a Chatbot for our Sales Force that would allow you to have official information necessary for your business, such as brochures, sales information, username and password recovery, discount coupon (Shopify). Develop the API to be able to communicate the service (Engage) with our systems and allow you to personalize users. In addition, it was used to send communication every week by the Marketing area. It was also used to send notifications of digital Events, such as personalized invitations, follow-ups, surveys, etc.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--a-Tb8yq_--/v1695950883/Proyectos/Tupperchat/tupperchat-001_ipklpj.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--vO0vwfFy--/v1695950883/Proyectos/Tupperchat/tupperchat-002_dexvs0.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--DXDZcNMt--/v1695950883/Proyectos/Tupperchat/tupperchat-003_b7zhka.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--m8Lu1R4z--/v1695950884/Proyectos/Tupperchat/tupperchat-004_l4pmhe.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--it4Erm49--/v1695950884/Proyectos/Tupperchat/tupperchat-005_tt1pgo.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--Ulyalplj--/v1695950884/Proyectos/Tupperchat/tupperchat-006_yx3kiq.jpg",
        ],
        technologies: "HTML, CSS, JavaScript, .NET, NodeJs",
      },
      {
        id: 11,
        date: "43101",
        brick: 4,
        title: "Voting system for RRHH New Year's Eve dinner",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--1JSxOfLn--/v1695785091/Proyectos/Rifas%20digitales/rifas-thumbnail_sqolws.png",
        isFeatured: false,
        description: "",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--1JSxOfLn--/v1695785091/Proyectos/Rifas%20digitales/rifas-thumbnail_sqolws.png",
        ],
        technologies: "HTML, CSS, JavaScript",
      },
      {
        id: 12,
        date: "42370",
        brick: 4,
        title: "Casino-type games for convention",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Mobile",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--7KNPEzIr--/ar_1:1,c_fill,g_auto,w_1000/v1695438921/Proyectos/Juegos%20Casino/casino-thumbnail_dwhc8c.png",
        isFeatured: false,
        description:
          "Development of Casino games (Slot Machines and Memory Cards) in order to entertain and compete among attendees at the 2016 convention.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--5g0D0mBc--/v1695438921/Proyectos/Juegos%20Casino/casino-thumbnail_dwhc8c.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--XtinsDvh--/v1695438902/Proyectos/Juegos%20Casino/casino-001_aeoe3y.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--ohJkRdl0--/v1695438924/Proyectos/Juegos%20Casino/casino-002_q0hcml.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--axhBC6jT--/v1695438919/Proyectos/Juegos%20Casino/casino-003_dxcwao.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--QibdcicN--/v1695438984/Proyectos/Juegos%20Casino/casino-004_fsx0cj.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--lmKTmwwB--/v1695438913/Proyectos/Juegos%20Casino/casino-005_wb7ixe.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--foprnrLa--/v1695438916/Proyectos/Juegos%20Casino/casino-006_fallyr.jpg",
        ],
        technologies: "Unity",
      },
      {
        id: 13,
        date: "42005",
        brick: 4,
        title: "Micrositio interno #HoyNoCircula",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--h8k6TdL7--/v1695693438/Proyectos/Mapa%20Reclutamiento/reclutando-thumbnail_qgmby2.png",
        isFeatured: false,
        description:
          "Todos los empleados pueden ver quiénes son sus vecinos para compartir el coche a través de una aplicación interna.",
        screenshots: [""],
        technologies: "HTML, CSS, JavaScript",
      },
      {
        id: 14,
        date: "42005",
        brick: 4,
        title: "Tuppercup/Tuppercup Latam Landingpage",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--KbPFqPp8--/ar_1:1,c_fill,g_auto,w_1000/v1695694369/Proyectos/Tuppercup/tuppecup-thumbnail_mvjvcx.png",
        isFeatured: false,
        description:
          "Sales Challenges by countries where results and ranking are monitored. This site was made in HTML/CSS/JavaScript.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--pvMRXLeJ--/v1695694372/Proyectos/Tuppercup/tuppecup-001_ejv4c0.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--KbPFqPp8--/ar_1:1,c_fill,g_auto,w_1000/v1695694369/Proyectos/Tuppercup/tuppecup-thumbnail_mvjvcx.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--UanV_QPU--/v1695694524/Proyectos/Tuppercup/tuppecup-002_wlghgh.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--r3xil2VI--/v1695694370/Proyectos/Tuppercup/tuppecup-003_ozt4nx.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--_y3IR9az--/v1695694366/Proyectos/Tuppercup/tuppecup-004_uqmq8e.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--0hnDSQq5--/v1695694368/Proyectos/Tuppercup/tuppecup-005_gmsvxb.png",
        ],
        technologies: "HTML, CSS, JavaScript",
      },
      {
        id: 15,
        date: "41640",
        brick: 4,
        title: "App Passport to Success (iOS/Android)",
        client: "Tupperware Brands México",
        liveUrl: "https://youtu.be/mEJiwCCjgVA",
        category: "Mobile",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--xIsbzLNo--/t_Thumbnail/v1/Proyectos/Pasaporte%20al%20Exito/pasaporte-thumbnail_cwikk6.webp",
        isFeatured: true,
        description:
          "Application developed for the Sales Force and Distributor. Which had 2 main objectives; Keep track of the incentives that were provided to the Sales Force for Training and Sales. And the Distributor could register attendance at the training by scanning the Passport, whether digital or physical (QR).",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--lnP-sJ1v--/v1695354142/Proyectos/Pasaporte%20al%20Exito/pasaporte-003_edjbfz.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--m1_Wi5iI--/v1695354140/Proyectos/Pasaporte%20al%20Exito/pasaporte-005_vkquzb.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--NxqA_tu4--/v1695354138/Proyectos/Pasaporte%20al%20Exito/pasaporte-006_tkdinw.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--fgme1QLq--/v1695354141/Proyectos/Pasaporte%20al%20Exito/pasaporte-001_mzntr5.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--lxUr4UC9--/v1695354139/Proyectos/Pasaporte%20al%20Exito/pasaporte-002_hwdigr.jpg",
        ],
        technologies: "JavaScript, Appcelerator, .NET, Microsoft SQL Server",
      },
      {
        id: 16,
        date: "41640",
        brick: 4,
        title: "Microsite for characters (Pingüi, Frogy, Gussy, Dino, Fishy)",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Mobile",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--gAGxFkpd--/ar_1:1,c_fill,g_auto,w_1000/v1695698604/Proyectos/TupperKids/tupperkis_thumbnail_grrfky.png",
        isFeatured: false,
        description:
          "I developed the microsites for the characters of the Tupper Kids line, in each launch of a new character, casual games were created in Unity, in addition to making a landing page to see product information. This was done thanks to Unity for Web before Chrome blocked web content, plus games were made with Canvas.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--gAGxFkpd--/ar_1:1,c_fill,g_auto,w_1000/v1695698604/Proyectos/TupperKids/tupperkis_thumbnail_grrfky.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--1e27yAyj--/v1695698604/Proyectos/TupperKids/tupperkids_001_afig2g.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--GqG_9lhE--/v1695698604/Proyectos/TupperKids/tupperkids_0022_uwmehm.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--yp9Ie63t--/v1695698967/Proyectos/TupperKids/fishy_001_h5kmd5.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--tIbWkdwa--/v1695698967/Proyectos/TupperKids/fishy_002_zagcrz.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--u-QF7YR7--/v1695698967/Proyectos/TupperKids/fishy_003_uskyg1.png",
        ],
        technologies: "HTML, CSS, JavaScript, Unity, Canvas, Bootstrap",
      },
      {
        id: 17,
        date: "41640",
        brick: 4,
        title:
          "Micrositio para campañas de Reclutamiento 'Dibujando a México con una Sonrisa'",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--wjGWu7is--/ar_1:1,c_fill,g_auto,w_1000/v1695693438/Proyectos/Mapa%20Reclutamiento/reclutando-thumbnail_qgmby2.png",
        isFeatured: false,
        description:
          "Map to show the progress of Recruitment at the national level by Regions. There were different campaigns for a few years, so this site was built with HTML/CSS/JavaScript and CartoDB.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--wjGWu7is--/ar_1:1,c_fill,g_auto,w_1000/v1695693438/Proyectos/Mapa%20Reclutamiento/reclutando-thumbnail_qgmby2.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--l21DDZ----/v1695693439/Proyectos/Mapa%20Reclutamiento/reclutando-001_yf73jm.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--99-u_1FN--/v1695693440/Proyectos/Mapa%20Reclutamiento/reclutando-002_esmol2.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--Gp1lzugU--/v1695693441/Proyectos/Mapa%20Reclutamiento/reclutando-003_wjrimk.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--9IIvkD1i--/v1695693442/Proyectos/Mapa%20Reclutamiento/reclutando-004_n14fi1.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--a7UA95UG--/v1695693407/Proyectos/Mapa%20Reclutamiento/reclutando-005_qonbhs.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--L_1SecZ8--/v1695693439/Proyectos/Mapa%20Reclutamiento/reclutando-006_am1f8i.png",
        ],
        technologies: "HTML, CSS, JavaScript, CartoDB",
      },
      {
        id: 18,
        date: "41275",
        brick: 4,
        title: "App Digital Catalog of Experiences (iOS/Android)",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Mobile",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--rXnOHUfl--/t_Thumbnail/v1/Proyectos/Catalogo%20Digital/catalog-thumbnail_nawvyk.webp",
        isFeatured: true,
        description:
          "First App for Mexico showing the brochures digitally, allowing the Sales Force and Final Consumer to navigate through our brochures, consulting the product galleries, videos and other multimedia content. In addition to being able to share it via social networks.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--DqveSN2r--/v1695269849/Proyectos/Catalogo%20Digital/catalog-thumbnail-001_qqemil.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--URbl9vyp--/v1695269848/Proyectos/Catalogo%20Digital/catalog-thumbnail-002_cq80zl.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--TTSZeYdy--/v1695269847/Proyectos/Catalogo%20Digital/catalog-thumbnail-003_yntuce.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--9mqev43d--/v1695269846/Proyectos/Catalogo%20Digital/catalog-thumbnail-004_mzzjfp.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--uHDi7ta_--/v1695269843/Proyectos/Catalogo%20Digital/catalog-thumbnail-005_acqj0i.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--H2PBGna9--/v1695269845/Proyectos/Catalogo%20Digital/catalog-thumbnail-006_exu9z5.png",
        ],
        technologies: "JavaScript, Appcelerator, iOS, Android",
      },
      {
        id: 19,
        date: "41275",
        brick: 4,
        title: "Augmented Reality for digital catalog",
        client: "Tupperware Brands México",
        liveUrl: "https://youtu.be/PeOM2GmwEWA",
        category: "Mobile",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--04BJH1Y8--/ar_1:1,c_fill,g_auto,w_1000/v1695692302/Proyectos/AR%20para%20Catalogo/ar-thumbnail_ohaqte.jpg",
        isFeatured: false,
        description:
          "Augmented reality, object recognition, animation, video. Products designed by Romero Britto.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--K34WQe8t--/v1695692302/Proyectos/AR%20para%20Catalogo/ar-thumbnail_ohaqte.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--F79nwu4M--/v1695692302/Proyectos/AR%20para%20Catalogo/ar-001_zhctmt.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--37HjWQbK--/v1695692302/Proyectos/AR%20para%20Catalogo/ar-002_xhdby0.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--dtEW_H8L--/v1695692303/Proyectos/AR%20para%20Catalogo/ar-003_zfyzvq.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--U4sQ_w1Z--/v1695692302/Proyectos/AR%20para%20Catalogo/ar-004_ucxbfl.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--004kOt1J--/v1695692302/Proyectos/AR%20para%20Catalogo/ar-005_uw9ett.png",
        ],
        technologies: "HTML, CSS, JavaScript, Unity",
      },
      {
        id: 20,
        date: "40909",
        brick: 4,
        title: "App Porteo (Android)",
        client: "Tupperware Brands México",
        liveUrl: "",
        category: "Mobile",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--jsJrwPFS--/t_Thumbnail/v1/Proyectos/Porteo/porteo-thumbnail_rw9veu.webp",
        isFeatured: true,
        description:
          "Download and Delivery of orders to the Sales Force (GPS, Photography, status, etc.) Application used by the Plant Distribution area to deliver orders to the Promoters that are part of the Sales Force. The app could download the week's orders, mark them as delivered, by scanning the labels and entering delivery information. GPS was used to know the location of the delivery and map the Sales Force using a Map. There was also a Web module developed in Vue to carry out this process when orders were delivered to the Porteadores Warehouse. Developed the backend and web service in .NET and the database queries were in Microsoft SQL Server.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--X_RVQXK4--/v1695348809/Proyectos/Porteo/porteo-thumbnail-002_i7wlgk.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--jYWISeJ3--/v1695348809/Proyectos/Porteo/porteo-thumbnail-003_h0gleu.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--NngmalIm--/v1695348808/Proyectos/Porteo/porteo-thumbnail-004_vjx9jl.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--mFzSwLQG--/v1695348809/Proyectos/Porteo/porteo-thumbnail-005_srvy9k.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s---UNxM44l--/v1695348809/Proyectos/Porteo/porteo-thumbnail-006_avi2yh.jpg",
          "https://res.cloudinary.com/menikmati/image/upload/s--_Pt2cRtY--/v1695432267/Proyectos/Porteo/porteo-thumbnail-007_jc1ycl.png",
        ],
        technologies:
          "JavaScript, Appcelerator, .NET, Microsoft SQL Server, Vue",
      },
      {
        id: 21,
        date: "45658",
        brick: 4,
        title: "OnlyDevs",
        client: "Personal Project",
        liveUrl: "https://onlydevsmx.netlify.app/",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--ZVY4JAMn--/v1757294370/Proyectos/Personal/OnlyDevs/OnlyDevs-001_ilgy5b.webp",
        isFeatured: false,
        description:
          "OnlyDevs is a web application developed as part of an advanced frontend development course. The platform simulates a social network where users can share content (images and videos), interact through comments, and explore posts from other community members. The project integrates modern tools from the React ecosystem for global state management, form handling, and efficient data fetching, along with Firebase as the backend and cloud storage. The interface was built with Tailwind CSS, ensuring a responsive, clean, and user-friendly design. This project not only strengthened my expertise in React and its ecosystem but also reinforced best practices in building scalable applications focused on user experience.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s---75ohAVK--/v1757293340/Proyectos/Personal/OnlyDevs/OnlyDevs-002_e6emjo.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--4L3pA6hW--/v1757293339/Proyectos/Personal/OnlyDevs/OnlyDevs-003_xiv8ez.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--uQ75N9lb--/v1757293339/Proyectos/Personal/OnlyDevs/OnlyDevs-004_lh2red.webp",
        ],
        technologies:
          "React, Zustand, TanStack Query, React Hook Form, Firebase, Tailwind CSS",
      },
      {
        id: 22,
        date: "45658",
        brick: 4,
        title: "nmda solutions",
        client: "Personal Project",
        liveUrl: "https://nmdasolutions.com/",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--UgIE16g0--/v1757362488/Proyectos/Personal/Nmda/nmda-001_lhdznh.webp",
        isFeatured: false,
        description:
          "nmda solutions is a personal website built to offer web development and custom application services. The project follows a minimalist and professional approach, designed to attract potential clients looking for modern digital solutions. The site clearly presents the available services with a responsive layout, optimized for user experience. It was developed using HTML, JavaScript, SASS, and Tailwind, featuring a custom color palette and a modular structure to ensure scalability and easy maintenance.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--XvIcf9Ew--/v1757362488/Proyectos/Personal/Nmda/nmda-002_u3e0pw.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--LYyUbHFD--/v1757362488/Proyectos/Personal/Nmda/nmda-003_y5jati.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--rK5wcYNj--/v1757362488/Proyectos/Personal/Nmda/nmda-004_ajtqtt.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--FhirIV3f--/v1757362488/Proyectos/Personal/Nmda/nmda-005_q11ob8.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--fvZN7G_S--/v1760467480/Proyectos/Personal/Nmda/nmda-006_lsu8t6.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--p0amJYaV--/v1760467480/Proyectos/Personal/Nmda/nmda-007_wu8dcb.webp",
        ],
        technologies: "HTML, JavaScript, SASS, Tailwind CSS",
      },
      {
        id: 23,
        date: "45658",
        brick: 4,
        title: "CSS Practice Projects",
        client: "Learning Projects",
        liveUrl: "",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--uuujJcm5--/v1757374691/Proyectos/Personal/Practica%20CSS/practicas-thumbnail_vsxx4c.webp",
        isFeatured: false,
        description:
          "CSS Practice Projects – A collection of layouts, components, and responsive designs built during my CSS learning journey. These exercises allowed me to strengthen my understanding of HTML and CSS fundamentals, experiment with responsive design techniques, and apply best practices for styling and layouts. While these are practice projects, they showcase my ability to translate concepts into clean, functional, and visually appealing web pages.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--FDwT9Uir--/v1757377069/Proyectos/Personal/Practica%20CSS/001_r395rl.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--F7vk5nZQ--/v1757377070/Proyectos/Personal/Practica%20CSS/002_kluqck.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--a4f4bQbW--/v1757377071/Proyectos/Personal/Practica%20CSS/003_gvxa3k.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--CGniu6ms--/v1757377072/Proyectos/Personal/Practica%20CSS/004_f8x3ny.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--80_wEo0a--/v1757377074/Proyectos/Personal/Practica%20CSS/005_qfbh0e.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--pSMsNOSQ--/v1757377076/Proyectos/Personal/Practica%20CSS/006_at86zg.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--iRDbbOOW--/v1757377077/Proyectos/Personal/Practica%20CSS/007_jfi0ox.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--WlqCT29C--/v1757377078/Proyectos/Personal/Practica%20CSS/008_zwvhit.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--lgAKUFSY--/v1757377078/Proyectos/Personal/Practica%20CSS/009_cy5qjf.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--TvyuRW9e--/v1757377081/Proyectos/Personal/Practica%20CSS/010_iwam4p.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--WCLjrq8q--/v1757377082/Proyectos/Personal/Practica%20CSS/011_u9l0c6.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--cR3VgJTc--/v1757377082/Proyectos/Personal/Practica%20CSS/012_cmj6em.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--rWNuXyBE--/v1757377082/Proyectos/Personal/Practica%20CSS/013_sizkuw.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--tOCzXAgu--/v1757377083/Proyectos/Personal/Practica%20CSS/014_zyn612.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--4Aob0l2Q--/v1757377085/Proyectos/Personal/Practica%20CSS/015_n1gwe3.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--LK3a9eyl--/v1757377085/Proyectos/Personal/Practica%20CSS/016_tocwpv.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--tLPVba7y--/v1757377086/Proyectos/Personal/Practica%20CSS/017_nypxyr.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--jMLOV8F_--/v1757377086/Proyectos/Personal/Practica%20CSS/018_edixkq.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--dJN2YqIy--/v1757377088/Proyectos/Personal/Practica%20CSS/019_boulyg.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--5rZGH7gC--/v1757377068/Proyectos/Personal/Practica%20CSS/020_tldo7a.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--M_pUb0ZR--/v1757377068/Proyectos/Personal/Practica%20CSS/021_xqu2ds.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--TaxDaGFa--/v1757377069/Proyectos/Personal/Practica%20CSS/022_fyiuc4.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--RZOViIb1--/v1757377069/Proyectos/Personal/Practica%20CSS/023_jrbinu.webp",
        ],
        technologies:
          "HTML, CSS, JavaScript, SASS, Flexbox, Grid, Responsive Design, Tailwind CSS",
      },
      {
        id: 24,
        date: "45659",
        brick: 4,
        title: "Django Ecommerce",
        client: "Personal Project",
        liveUrl: "https://jimmyegc.pythonanywhere.com/",
        category: "Web",
        githubUrl: "",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--9tCv3zgh--/v1760641512/Proyectos/Personal/Ecommerce/cover_l9yvzd.webp",
        isFeatured: false,
        description:
          "This project is an online store built with Django, designed to deliver a modern and functional shopping experience. It includes product management, shopping cart functionality, user authentication, and secure payment integration with Stripe. Developed as part of my professional growth, this project allowed me to master the full development cycle of a web application with a focus on clean architecture, usability, and good development practices.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--oI85yk_I--/v1760641512/Proyectos/Personal/Ecommerce/001_j3b1zx.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--fxWITkBh--/v1760641512/Proyectos/Personal/Ecommerce/002_ijyr7k.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--NLzkFl4Z--/v1760641513/Proyectos/Personal/Ecommerce/003_p8v9ii.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--nXPAppks--/v1760641513/Proyectos/Personal/Ecommerce/004_m28omn.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--eqTg-6Ik--/v1760641512/Proyectos/Personal/Ecommerce/005_nihyed.webp",
        ],
        technologies:
          "HTML, CSS, JavaScript, Django, MySQL, Stripe, Tailwind CSS",
      },
      {
        id: 25,
        date: "45660",
        brick: 4,
        title: "Kiiro App - Personal Expense Tracker",
        client: "Personal Project",
        liveUrl: "https://kiiro-control-gastos.netlify.app/",
        category: "Web App",
        githubUrl: "https://github.com/jimmyegc/react-control-gastos-template",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--cLxaSyqD--/v1762820261/Proyectos/Kiiro/kiiro-cover_j46zqe.webp",
        isFeatured: false,
        description:
          "Kiiro App is a modern web application for managing personal expenses, built with React, Supabase, and Vite. It features dark and light modes, interactive reports, category management, and secure cloud storage. The design emphasizes a minimalistic and professional user experience.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--pZNCpNuQ--/v1762820261/Proyectos/Kiiro/kiiro-001_wwi8ho.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--ydu6uNfN--/v1762820261/Proyectos/Kiiro/kiiro-002_yezpk9.webp",
          "https://res.cloudinary.com/menikmati/image/upload/s--BNMoLT_X--/v1762820261/Proyectos/Kiiro/kiiro-003_jgc2br.webp",
        ],
        technologies: "React, Vite, Supabase, Styled Components, Chart.js",
      },
      {
        id: 26,
        date: "45690",
        brick: 4,
        title: "Migración de Sistema de Facturación de VB6 a React",
        client: "Cliente Empresarial (Sistema Interno)",
        liveUrl: "",
        category: "Web App / Modernización de Software",
        githubUrl: "https://github.com/jimmyegc/react-invoice-app",
        thumbnail:
          "https://res.cloudinary.com/menikmati/image/upload/s--LgLu_zst--/v1772064362/Proyectos/Migracion%20de%20Facturacion/screenshot-01_ki7rhd.png",
        isFeatured: false,
        description:
          "Proyecto de modernización tecnológica enfocado en migrar un sistema de facturación desarrollado en Visual Basic 6 con base de datos en Microsoft Access hacia una arquitectura web moderna basada en React y Supabase. La migración implicó rediseñar la interfaz, optimizar la estructura de datos y mejorar la experiencia de usuario sin afectar la lógica de negocio existente. Se implementó manejo de estado global con Zustand, gestión de datos asíncrona con TanStack Query y validación robusta de formularios con React Hook Form. El nuevo sistema ofrece mayor escalabilidad, mantenimiento simplificado, acceso en la nube y mejor rendimiento, eliminando dependencias legacy.",
        screenshots: [
          "https://res.cloudinary.com/menikmati/image/upload/s--LgLu_zst--/v1772064362/Proyectos/Migracion%20de%20Facturacion/screenshot-01_ki7rhd.png",
          "https://res.cloudinary.com/menikmati/image/upload/s--Coz9_4fp--/v1772064362/Proyectos/Migracion%20de%20Facturacion/screenshot-02_eh0b0q.png",
        ],
        technologies:
          "React, Zustand, TanStack Query, React Hook Form, Tailwind CSS, Supabase, PostgreSQL",
      },
    ],
    education: [
      {
        name: "Instituto Tecnológico de Ciudad Madero",
        idCard: "",
        endDate: "",
        urlCard: "https://www.cedulaprofesional.sep.gob.mx/",
        location: "",
        startDate: "",
        description: ["Computer Systems Engineering"],
      },
    ],
    experience: [
      {
        name: "Freelancer",
        endDate: "Actually",
        location: "Cuajimalpa de Morelos, México",
        startDate: "Jan 2024",
        description: [
          "✓ I was part of the Frontend development team for the b360.ai system, contributing to the implementation of key modules for configuration, operations, and reporting using technologies such as React, TypeScript, React Hook Form, and Zustand. I supported code management through GitBucket and deployment processes using NGINX and AWS. This development enabled the operation of a multi-account call center, providing support for clients such as Ualá and Telcel (prototype phase), streamlining internal processes and enhancing the end-user experience.",
        ],
      },
      {
        name: "Tupperware Brands México",
        endDate: "Jul 2023",
        location: "Paseo de los Laureles, 458, Cuajimalpa de Morelos, México",
        startDate: "Jun 2012",
        description: [
          "✓ Developed the first mobile applications for the company (Digital Catalog/Porting/Passport to Success) using Appcelerator (JavaScript), .NET with SQL Server for the backend.",
          "✓ Developed games/augmented reality in Unity used for new product launches and Convention events.",
          "✓ I developed various Web applications using web technologies (HTML/CSS/JavaScript) and in the last 4 years I was working with: NodeJs, React, VueJs, Tailwind CSS. The applications were focused on the area of Promotions, Marketing, HR, Training , Communication and Events.",
          "✓ Provide in-person training and email support on our digital tools to our Sales Force throughout the country, in addition to generating content, solutions, video tutorials, etc.",
          "✓ Also provide support to integrate third-party solutions with those of the company.",
        ],
      },
      {
        name: "Global Logos System, S.A. de C.V.",
        endDate: "May 2012",
        location:
          "Av. Santa Fe 170, Santa Fe, Zedec Sta Fé, Álvaro Obregón, 01210 Ciudad de México, CDMX",
        startDate: "Apr 2011",
        description: [
          "✓ Maintenance, Development and Implementation of some modules for our main client (FEMSA) such as:",
          "   - DILE (Comprehensive Diagnostic Packaging Lines) Jugos del Valle of Tepotzotlán. (.NET/SQL Server)",
          "   - NAP (Notifier of Automatic Production) (.NET/SQL Server).",
          "✓ Research and development of technology trends such as the use of Microsoft Kinect to use presentations using gestures and voice commands.",
          "✓ I trained the team for the development of mobile applications using the Appcelerator framework (JavaScript), in addition to developing an App that covered the entire development life cycle for iOS/Android called Cazabaches.",
        ],
      },
      {
        name: "Amports de México S.A. de C.V.",
        endDate: "Dec 2010",
        location:
          "Prol. P.º de la Reforma 1235, Lomas de Santa Fe, Contadero, Cuajimalpa de Morelos, 05348 Ciudad de México, CDMX",
        startDate: "Nov 2008",
        description: [
          "✓ Support, development and maintenance of company systems in its 6 locations (Altamira, Mazatlán, Lázaro Cárdenas, Toluca and Santa Fe Santiago Tianguistenco) such as the Billing System (SIAF), Inventory, Service Loading, Operations, etc. (Visual Basic/SQL Server)",
          "✓ Administration of VMWare, email and applications for our internal users in all locations.",
          "✓ Support, development and maintenance of mobile applications made with Windows Mobile (Intermec 730, CK30, CN3, Motorola MC9090).",
        ],
      },
      {
        name: "Freelancer",
        endDate: "Oct 2008",
        location: "Tampico, Tamaulipas, México",
        startDate: "Aug 2004",
        description: [
          "✓ Responsible for developing and implementation of (Desktop/Web) applications for our customers for Invoicing, Inventory Control, Sales Control, Point of Sale, Stock Control, Control Branch, Control Software downloads (FTP), control patients, Manager gynecology, control of loans and clients, mechanical integrity of pressure vessels, report generator, management of a clinical laboratory, inventory Control (Cylinders and containers). Using (PHP/Visual Basic/Microsoft Access/MySQL)",
          "✓ Support and preventive/corrective maintenance of computer equipment.",
          "✓ Quotes and sales of computer equipment.",
        ],
      },
    ],
    socialMedia: {
      email: "",
      github: "https://github.com/jimmyegc",
      twitter: "",
      facebook: "",
      linkedin: "https://www.linkedin.com/in/jimmyegc",
    },
    jobDescription: "Full Stack Developer",
  },
  languageOptions: {
    en: "English",
    es: "Español",
  },
  resumeConfig: {
    summary: "Professional Summary",
    professionalExperience: "Professional Experience",
    education: "Education",
    skills: "Technical Skills",
    languages: "Languages",
  },
};
